### ISSUE TITLE
[BUG] ':' character in clab binds causes processing errors

### ISSUE THREAD

**Issue by aceplean** [ipspace/netlab#1402]
### Describe the bug

cEOS has a habit of creating interface Ma0 when a Ma1 should exist; this can have some subtle issues with Cloudvision. Arista recommends mapping the interface names.
In containerlab this is done with a json file bind-mounted in flash: of the router (/mnt/flash)
Netlab appears to allow containerlab binds but they are not properly created. I thought that my netlab may be dated (1.7) so I moved to latest one 1.9.1.
Same situation.

### To Reproduce

Use minimal topology example below

### Expected behavior

Create binds that containerlab understands; or more accurately: correctly create yaml sequence for binds.

### Lab topology

```
provider: clab

defaults.devices.eos.clab.image: ceos:4.30.5M

nodes:
  temgm1:
    device: eos
    clab:
      binds:
        mymapping_json: '/mnt/flash/EosIntfMapping_json:ro'
```
It produces this clab.yml output:
```
name: topos

mgmt:
  network: netlab_mgmt
  ipv4-subnet: 192.168.121.0/24
  # Note: 'start' not validated
topology:
  nodes:
    temgm1:
      mgmt-ipv4: 192.168.121.101
      kind: ceos
      env: {'INTFTYPE': 'et', 'CLAB_MGMT_VRF': 'management'}
      image: ceos:4.30.5M
      runtime: docker
      binds:
      - mymapping_json:/mnt/flash/EosIntfMapping_json:ro
```
The listed binds - just one in the example- not correctly indented, cause errors further:

```
[CREATED] provider configuration file: clab.yml
Traceback (most recent call last):
  File "/home/aceplean/netlab/venv/bin/netlab", line 12, in <module>
    netsim.cli.lab_commands(__file__)
  File "/home/aceplean/netlab/venv/lib64/python3.8/site-packages/netsim/cli/__init__.py", line 333, in lab_commands
    mod.run(sys.argv[arg_start:])   # type: ignore
  File "/home/aceplean/netlab/venv/lib64/python3.8/site-packages/netsim/cli/up.py", line 371, in run
    run_up(cli_args)
  File "/home/aceplean/netlab/venv/lib64/python3.8/site-packages/netsim/cli/up.py", line 306, in run_up
    topology = get_topology(args,cli_args)
  File "/home/aceplean/netlab/venv/lib64/python3.8/site-packages/netsim/cli/up.py", line 91, in get_topology
    topology = create.run(cli_args,'up','Create configuration files, start a virtual lab, and configure it',up_args_parser)
  File "/home/aceplean/netlab/venv/lib64/python3.8/site-packages/netsim/cli/create.py", line 93, in run
    output_module.write(topology)
  File "/home/aceplean/netlab/venv/lib64/python3.8/site-packages/netsim/outputs/provider.py", line 37, in write
    write_provider_file(providers.select_topology(topology,topology.provider),topology.provider,filename)
  File "/home/aceplean/netlab/venv/lib64/python3.8/site-packages/netsim/outputs/provider.py", line 14, in write_provider_file
    p_module.create(topology,filename)
  File "/home/aceplean/netlab/venv/lib64/python3.8/site-packages/netsim/providers/__init__.py", line 206, in create
    self.post_configuration_create(topology)
  File "/home/aceplean/netlab/venv/lib64/python3.8/site-packages/netsim/providers/clab.py", line 179, in post_configuration_create
    self.create_extra_files(n,topology)
  File "/home/aceplean/netlab/venv/lib64/python3.8/site-packages/netsim/providers/__init__.py", line 159, in create_extra_files
    bind_dict = filemaps.mapping_to_dict(binds)
  File "/home/aceplean/netlab/venv/lib64/python3.8/site-packages/netsim/data/filemaps.py", line 39, in mapping_to_dict
    return { k:v for k,v in [ l.split(':') for l in m ] }
  File "/home/aceplean/netlab/venv/lib64/python3.8/site-packages/netsim/data/filemaps.py", line 39, in <dictcomp>
    return { k:v for k,v in [ l.split(':') for l in m ] }
ValueError: too many values to unpack (expected 2)
```

### Version

netlab version 1.9.1

### Additional context

A closed bug #597 exists for this issue, the workaround at that time was to avoid dots in key names; I tried that here unsuccessfully.

**Comment by jbemmel** [comment]
The issue is the trailing ":ro", we can probably add quotes around the value to avoid that but in the meantime try:
```
binds:
        mymapping_json: '/mnt/flash/EosIntfMapping_json'
```

**Comment by aceplean** [comment]
Confirmed, works without the readonly modifier.
thanks

**Comment by ipspace** [comment]
@aceplean: Could you please post the content of that mapping file so I can test a few more things?

If nothing else, the management interface name would also have to be changed in device settings. Also, I would like to add this behavior to cEOS caveats.

**Comment by aceplean** [comment]
Sure, here you go. The mapping for et1 and et2 are shown just for exemplification and not related to the management interface issue subject of this ticket.
```
{
  "ManagementIntf": {
    "eth0": "Management1"
  },
  "EthernetIntf": {
    "et1":"Ethernet100",
    "et2":"Ethernet200"
  }
}
```

**Comment by ipspace** [comment]
> Sure, here you go.

Thank you, will add to the caveats.
