### ISSUE TITLE
[BUG] Error when omitting gateway module

### ISSUE THREAD

**Issue by jbemmel** [ipspace/netlab#671]
### Describe the bug

Code tries to iterate over link.gateway, in a case where it is still a bool (unresolved to a dict)

### To Reproduce

netlab up integration/evpn/vxlan-bridging-leaf-spine.yml -s nodes.l1.device=frr -p clab -d srlinux

Traceback (most recent call last):
  File "/home/jeroen/srlinux/netlab/netlab", line 8, in <module>
    netsim.cli.lab_commands()
  File "/home/jeroen/srlinux/netlab/netsim/cli/__init__.py", line 157, in lab_commands
    mod.run(sys.argv[arg_start:])   # type: ignore
  File "/home/jeroen/srlinux/netlab/netsim/cli/up.py", line 69, in run
    topology = create.run(cli_args,'up','Create configuration files, start a virtual lab, and configure it',up_args_parser)
  File "/home/jeroen/srlinux/netlab/netsim/cli/create.py", line 76, in run
    augment.main.transform(topology)
  File "/home/jeroen/srlinux/netlab/netsim/augment/main.py", line 85, in transform
    transform_data(topology)
  File "/home/jeroen/srlinux/netlab/netsim/augment/main.py", line 64, in transform_data
    augment.links.transform(topology.links,topology.defaults,topology.nodes,topology.pools)
  File "/home/jeroen/srlinux/netlab/netsim/augment/links.py", line 774, in transform
    set_default_gateway(link,nodes)
  File "/home/jeroen/srlinux/netlab/netsim/augment/links.py", line 719, in set_default_gateway
    if not 'gateway' in link or not 'ipv4' in link.gateway: # Didn't find a usable gateway, exit
TypeError: argument of type 'bool' is not iterable

### Expected behavior
Topology should deploy

### Lab topology

```
message: |
  This test case builds a leaf-and-spine fabric with VLAN-over-VXLAN
  bridging. The leaf switches are doing VLAN/VXLAN encap/decap, the
  spine switches are IP routers running OSPF, BGP, and EVPN.

  Assuming the 'vxlan-bridging' test case succeeded, this test case
  validates that the EVPN route reflectors, MTU settings and ECMP work as expected.

  * h1 and h2 should be able to ping each other using 1500 bytes IP payload, e.g.
    docker exec -it clab-evpn-h2 ping 172.16.0.1 -s 1472
  * h3 and h4 should be able to ping each other

  Please note it might take a while for the lab to work due to
  STP learning phase

  To change the devices under test, use netlab up -d parameter
groups:
  hosts:
    members: [ h1, h2, h3, h4 ]
    device: linux
  leafs:
    members: [ l1, l2 ]
    module: [ vlan,vxlan,ospf,bgp,evpn,vrf ] # added vrf, but not gateway
  spines:
    members: [ s1, s2 ]
    module: [ ospf,bgp,evpn,gateway,vrf ]  # added gateway, vrf
    node_data:
      bgp.rr: True

bgp.as: 65000
evpn.vlans: [ red, blue ]

vlans:
  red:
    mode: bridge
  blue:
    mode: route
    gateway: True # Added

nodes:
  h1:
  h2:
  h3:
  h4:
  l1:
  l2:
  s1:
  s2:

links:
- h1:
  l1:
    vlan.access: red
- h2:
  l2:
    vlan.access: red
- h3:
  l1:
    vlan.access: blue
- h4:
  l2:
    vlan.access: blue
- l1:
  s1:
  mtu: 1550 # Increased to support VXLAN
- l1:
  s2:
  mtu: 1550
- l2:
  s1:
  mtu: 1550
- l2:
  s2:
  mtu: 1550
```

### Output

```
Traceback (most recent call last):

  File "/home/jeroen/srlinux/netlab/netlab", line 8, in <module>

    netsim.cli.lab_commands()

  File "/home/jeroen/srlinux/netlab/netsim/cli/__init__.py", line 157, in lab_commands

    mod.run(sys.argv[arg_start:])   # type: ignore

  File "/home/jeroen/srlinux/netlab/netsim/cli/up.py", line 69, in run

    topology = create.run(cli_args,'up','Create configuration files, start a virtual lab, and configure it',up_args_parser)

  File "/home/jeroen/srlinux/netlab/netsim/cli/create.py", line 76, in run

    augment.main.transform(topology)

  File "/home/jeroen/srlinux/netlab/netsim/augment/main.py", line 85, in transform

    transform_data(topology)

  File "/home/jeroen/srlinux/netlab/netsim/augment/main.py", line 64, in transform_data

    augment.links.transform(topology.links,topology.defaults,topology.nodes,topology.pools)

  File "/home/jeroen/srlinux/netlab/netsim/augment/links.py", line 774, in transform

    set_default_gateway(link,nodes)

  File "/home/jeroen/srlinux/netlab/netsim/augment/links.py", line 719, in set_default_gateway

    if not 'gateway' in link or not 'ipv4' in link.gateway: # Didn't find a usable gateway, exit

TypeError: argument of type 'bool' is not iterable
```

### Version

dev branch

**Comment by ipspace** [comment]
Root cause: **gateway** attribute set on a link that has no attached nodes with **gateway** module.

Minimum topology needed to reproduce the bug:

```
nodes:
  h:
    device: linux
  s:
    device: eos
  r:
    device: eos
    module: [ gateway ]

links:
- h:
  s:
  gateway: True
```
